<?php

declare(strict_types=1);

namespace Tests\JpmMartin\SyliusShippingCarriersPlugin\Unit\Docs;

use JpmMartin\SyliusShippingCarriersPlugin\DependencyInjection\Configuration;
use JpmMartin\SyliusShippingCarriersPlugin\Destination\DestinationType;
use JpmMartin\SyliusShippingCarriersPlugin\Shipping\Calculator\CarrierRateCalculator;
use JpmMartin\SyliusShippingCarriersPlugin\Shipping\FailurePolicy;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Component\Config\Definition\Processor;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Yaml\Yaml;

/**
 * Holds `docs/extending.md` to the code, in both directions.
 *
 * The page is the plugin's public surface and the versioning promise is made about it, so a name on it that does
 * not exist is a broken promise, and a class that is neither on it nor marked `@internal` is a promise nobody meant
 * to make. Both fail here rather than in a release.
 */
final class ExtendingSurfaceTest extends KernelTestCase
{
    private const ROOT = __DIR__ . '/../../..';

    private const DOCUMENT = self::ROOT . '/docs/extending.md';

    private const PLUGIN_NAMESPACE = 'JpmMartin\\SyliusShippingCarriersPlugin\\';

    public function testEveryClassNamedExists(): void
    {
        $names = $this->spansMatching('/^JpmMartin\\\\SyliusShippingCarriersPlugin\\\\[A-Za-z0-9_\\\\]+$/');
        self::assertNotEmpty($names);

        foreach ($names as $name) {
            self::assertTrue(class_exists($name) || interface_exists($name), sprintf('%s is named in docs/extending.md and does not exist.', $name));
        }
    }

    public function testEveryServiceAndTagNamedIsDeclared(): void
    {
        $services = $this->contentsOf(self::ROOT . '/config/services', 'xml');
        $extension = (string) file_get_contents(self::ROOT . '/src/DependencyInjection/JpmMartinSyliusShippingCarriersExtension.php');
        $resources = array_keys($this->resources());

        foreach ($this->spansMatching('/^jpmmartin_carrier\.[a-z_.]*[a-z_]$/') as $name) {
            if (1 === preg_match('/^jpmmartin_carrier\.repository\.([a-z_]+)$/', $name, $match)) {
                self::assertContains($match[1], $resources, sprintf('%s names a resource the plugin does not declare.', $name));

                continue;
            }

            $declared = str_contains($services, sprintf('id="%s"', $name)) ||
                str_contains($services, sprintf('<tag name="%s"', $name)) ||
                str_contains($extension, sprintf("'%s'", $name));
            self::assertTrue($declared, sprintf('%s is named in docs/extending.md and is neither a service nor a tag of the plugin.', $name));
        }
    }

    public function testEveryHookAndHookableNamedIsRegistered(): void
    {
        $hooks = $this->hooks();

        foreach ($this->spansMatching('/^(sylius_admin|sylius_shop|jpmmartin_carrier_admin)\.[a-z_.]+$/') as $hook) {
            self::assertArrayHasKey($hook, $hooks, sprintf('%s is named as a hook and the plugin registers nothing on it.', $hook));
        }

        // The hooks table: every hookable a row names is registered on the hook the row names.
        preg_match_all('/^\| `([a-z_.]+)`[^|]*\| ([^|]+)\|$/m', $this->document(), $rows, \PREG_SET_ORDER);
        self::assertNotEmpty($rows, 'The hooks table was not found.');
        foreach ($rows as [, $hook, $cell]) {
            preg_match_all('/`([a-z_]+)`/', $cell, $hookables);
            foreach ($hookables[1] as $hookable) {
                self::assertContains($hookable, $hooks[$hook] ?? [], sprintf('Hookable "%s" is not registered on %s.', $hookable, $hook));
            }
        }
    }

    /**
     * Asked of the router of the test application, because the resource routes are generated by Sylius and are
     * named nowhere in the plugin's files. Each row's path is what follows the prefix a store mounts the routes under.
     */
    public function testEveryRouteNamedExistsAtThePathTheTableGivesIt(): void
    {
        self::bootKernel();
        /** @var RouterInterface $router */
        $router = self::getContainer()->get('router');
        $routes = $router->getRouteCollection();

        foreach ($this->spansMatching('/^jpmmartin_carrier_(admin|shop)_[a-z_]+$/') as $route) {
            self::assertNotNull($routes->get($route), sprintf('%s is named as a route and none exists.', $route));
        }

        preg_match_all('/^\| `(jpmmartin_carrier_[a-z_]+)` \| `([^`]+)` \|/m', $this->document(), $rows, \PREG_SET_ORDER);
        self::assertNotEmpty($rows, 'The routes table was not found.');
        foreach ($rows as [, $route, $path]) {
            self::assertStringEndsWith($path, (string) $routes->get($route)?->getPath(), sprintf('The path of %s.', $route));
        }
    }

    public function testEveryConsoleCommandNamedExists(): void
    {
        $sources = $this->contentsOf(self::ROOT . '/src', 'php');

        $commands = $this->spansMatching('/^jpmmartin:carrier:[a-z-]+$/');
        self::assertNotEmpty($commands);
        foreach ($commands as $command) {
            self::assertStringContainsString(sprintf("name: '%s'", $command), $sources, sprintf('Console command %s is named and none is declared.', $command));
        }
    }

    public function testEveryCalculatorNamedIsRegistered(): void
    {
        $services = $this->contentsOf(self::ROOT . '/config/services', 'xml');

        foreach ($this->spansMatching('/^[a-z]+_rate$/') as $calculator) {
            self::assertStringContainsString(sprintf('calculator="%s"', $calculator), $services, sprintf('Calculator %s is named and none is registered.', $calculator));
        }
    }

    /**
     * The resources table: each resource exists, with the contract and the model the row gives it.
     */
    public function testEveryResourceNamedHasTheClassesTheTableGivesIt(): void
    {
        $resources = $this->resources();

        preg_match_all('/^\| `([a-z_]+)` \| `([A-Za-z\\\\]+)` \| `([A-Za-z\\\\]+)` \|$/m', $this->document(), $rows, \PREG_SET_ORDER);
        self::assertCount(\count($resources), $rows, 'Every resource the plugin declares has a row, and nothing else does.');
        foreach ($rows as [, $resource, $interface, $model]) {
            self::assertArrayHasKey($resource, $resources, sprintf('%s is named as a resource and the plugin does not declare it.', $resource));
            self::assertSame($interface, $resources[$resource]['interface'], sprintf('The contract of %s.', $resource));
            self::assertSame($model, $resources[$resource]['model'], sprintf('The model of %s.', $resource));
        }
    }

    /**
     * What the page says a store has already saved is what the code reads: these values live in the database of every
     * installation, so the page and the code must not drift apart.
     */
    public function testTheStoredValuesNamedAreTheOnesTheCodeUses(): void
    {
        $spans = $this->spansMatching('/^[a-z_]+$/');

        foreach ([
            CarrierRateCalculator::SERVICE,
            CarrierRateCalculator::FAILURE_POLICY,
            CarrierRateCalculator::FLAT_AMOUNT,
            FailurePolicy::HIDE,
            FailurePolicy::FLAT,
            DestinationType::RESIDENTIAL,
            DestinationType::COMMERCIAL,
        ] as $value) {
            self::assertContains($value, $spans, sprintf('"%s" is stored by the plugin and docs/extending.md does not name it.', $value));
        }
    }

    public function testEveryClassIsEitherNamedOrInternal(): void
    {
        $named = array_flip($this->spansMatching('/^JpmMartin\\\\SyliusShippingCarriersPlugin\\\\[A-Za-z0-9_\\\\]+$/'));
        $unclassified = [];
        $wrongly = [];

        foreach ($this->files(self::ROOT . '/src', 'php') as $file) {
            $relative = substr($file, \strlen(self::ROOT . '/src/'), -4);
            // Migrations are run, never extended: neither public nor internal.
            if (str_starts_with($relative, 'Migrations/')) {
                continue;
            }
            $class = self::PLUGIN_NAMESPACE . str_replace('/', '\\', $relative);
            $internal = str_contains((string) file_get_contents($file), '@internal');

            if (!isset($named[$class]) && !$internal) {
                $unclassified[] = $class;
            }
            if (isset($named[$class]) && $internal) {
                $wrongly[] = $class;
            }
        }

        self::assertSame([], $unclassified, 'Named in docs/extending.md or marked @internal: every class chooses. These chose neither.');
        self::assertSame([], $wrongly, 'Named as public in docs/extending.md and marked @internal at once.');
    }

    private function document(): string
    {
        return (string) file_get_contents(self::DOCUMENT);
    }

    /** @return list<string> */
    private function spansMatching(string $pattern): array
    {
        preg_match_all('/`([^`\n]+)`/', $this->document(), $matches);

        return array_values(array_unique(array_filter($matches[1], static fn (string $span): bool => 1 === preg_match($pattern, $span))));
    }

    /** @return array<string, list<string>> hook name to its hookables, as the plugin registers them */
    private function hooks(): array
    {
        $hooks = [];
        foreach ($this->files(self::ROOT . '/config/twig_hooks', 'yaml') as $file) {
            /** @var array{sylius_twig_hooks?: array{hooks?: array<string, array<string, mixed>>}} $parsed */
            $parsed = (array) Yaml::parseFile($file);
            foreach ($parsed['sylius_twig_hooks']['hooks'] ?? [] as $hook => $hookables) {
                $hooks[$hook] = array_merge($hooks[$hook] ?? [], array_map('strval', array_keys($hookables)));
            }
        }

        return $hooks;
    }

    /** @return array<string, array{model: string, interface: string}> resource name to its default classes */
    private function resources(): array
    {
        /** @var array{resources: array<string, array{classes: array{model: string, interface: string}}>} $config */
        $config = (new Processor())->processConfiguration(new Configuration(), []);

        return array_map(static fn (array $resource): array => [
            'model' => $resource['classes']['model'],
            'interface' => $resource['classes']['interface'],
        ], $config['resources']);
    }

    private function contentsOf(string $directory, string $extension): string
    {
        return implode("\n", array_map(static fn (string $file): string => (string) file_get_contents($file), $this->files($directory, $extension)));
    }

    /** @return list<string> */
    private function files(string $directory, string $extension): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($directory, \FilesystemIterator::SKIP_DOTS));
        /** @var \SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->getExtension() === $extension) {
                $files[] = $file->getPathname();
            }
        }
        sort($files);

        return $files;
    }
}
