# Define your own shop Twig hooks here.
#
# sylius_twig_hooks:
#     hooks:
#         'sylius_shop.checkout.select_shipping.content':
#             some_block:
#                 template: '@JpmMartinSyliusShippingCarriersPlugin/shop/…'
#                 priority: 0
