<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SymfonySetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->importNames();
    $rectorConfig->parallel();

    $rectorConfig->paths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ]);

    $rectorConfig->skip([
        // Generated by the test application at runtime.
        __DIR__ . '/tests/TestApplication/var',
    ]);

    $rectorConfig->sets([
        // Matches `php: ^8.2` in composer.json. Do NOT raise this to 8.3/8.4:
        // the package must keep running on the lowest PHP version it declares.
        LevelSetList::UP_TO_PHP_82,

        // rector/rector 1.2.10 ships SymfonySetList up to SYMFONY_71 only.
        // The stack resolves Symfony 7.4, so there is no set covering 7.2–7.4 yet.
        SymfonySetList::SYMFONY_71,

        SetList::CODE_QUALITY,
        SetList::DEAD_CODE,
        SetList::EARLY_RETURN,
        SetList::TYPE_DECLARATION,
    ]);
};
